#helm:generate helm tpl -d $HELM_GENERATE_DIR/tpl/generate_params.toml -o $HELM_GENERATE_DIR/manifests/deis-logger-rc.yaml $HELM_GENERATE_DIR/tpl/deis-logger-rc.yaml
apiVersion: v1
kind: ReplicationController
metadata:
  name: deis-logger
  namespace: deis
  labels:
    heritage: deis
spec:
  replicas: 1
  selector:
    app: deis-logger
  template:
    metadata:
      labels:
        app: deis-logger
    spec:
      containers:
      - name: deis-logger
        image: quay.io/{{.logger.org}}/logger:{{env "LOGGER_GIT_TAG" | default .logger.dockerTag}}
        imagePullPolicy: {{.logger.pullPolicy}}
        ports:
        - containerPort: 8088
          name: http
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8088
          initialDelaySeconds: 1
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8088
          initialDelaySeconds: 1
          timeoutSeconds: 1
