apiVersion: v1
kind: Secret
metadata:
  name: database-creds
  namespace: deis
  labels:
    app: deis-database
    heritage: deis
data:
  user: {{ if or (eq (env "DATABASE_LOCATION") "off-cluster") (eq .database_location "off-cluster") }}{{ or (env "DATABASE_USERNAME") .database.username | b64enc }}{{ else }}{{ randAlphaNum 32 | b64enc }}{{ end }}
  password: {{ if or (eq (env "DATABASE_LOCATION") "off-cluster") (eq .database_location "off-cluster") }}{{ or (env "DATABASE_PASSWORD") .database.password | b64enc }}{{ else }}{{ randAlphaNum 32 | b64enc }}{{ end }}
